spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minha_vez_db?createDatabaseIfNotExist=true
    username: ${USUARIO_BD}
    password: ${SENHA_BD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5785
      expiration: 86400000 # a day
